harfbuzz/harfrust

Cargo.toml, README.md, examples/shape.rs, src/hb/face.rs, src/hb/shape_wasm.rs, tests/shaping/main.rs
Fixes #1 and gets us building w/new name.
[rendered](https://github.com/harfbuzz/harfruzz/tree/readme)
=> Update readme and name

Cargo.toml, src/hb/buffer.rs, src/hb/face.rs, src/hb/fonta/font.rs, src/hb/fonta/mod.rs, src/hb/fonta/ot/contextual.rs, src/hb/fonta/ot/gpos/pair.rs, src/hb/fonta/ot/gsub/multiple.rs, src/hb/fonta/ot/gsub/single.rs, src/hb/fonta/ot/lookup_cache.rs
Step toward #3
Migration to read-fonts instead of skrifa left for a follow-on
Some of the gid handling is dodgy wrt 16 vs 32 bit. Fully migration to read-fonts should tidy that up.
=> Use a published version of skrifa

Cargo.toml, README.md, src/hb/buffer.rs, src/hb/face.rs, src/hb/shape_wasm.rs, src/lib.rs
We already depend on `bytemuck_derive` through `font-types`, so we might as well use this to remove any remaining unsafe code.
=> Forbid unsafe code

src/lib.rs
That is `Tag` and `F2Dot14`. Looks like `FontRef` is already available.
=> Re-export types used in the public API

Cargo.lock, Cargo.toml, src/hb/charmap.rs
Currently based on a git dependency so shouldn't be merged until a new version of read-fonts is released.
=> Add support for cmap format 13

src/hb/aat_layout_kerx_table.rs, src/hb/kerning.rs, src/hb/ot/gpos/cursive.rs, src/hb/ot/gpos/mark.rs, src/hb/ot/gpos/pair.rs, src/hb/ot_layout.rs, src/hb/ot_layout_gsubgpos.rs
Some sketch on how to remove the circular cycle between skippy-iter and apply-context.
=> Skippy iter  refactor

src/hb/ot_shape.rs
Not sure why this block was not ported before.
=> [ot_shape] Sync propagate_flags with hb

README.md
- Spell HarfBuzz and HarfRust consistently
- Update outdated sections
- Remove redundant ones
- Improve the tune of the text a bit (the bits inherited from the original RustyBuzz README)
=> Edit README a bit

.github/workflows/main.yml, src/hb/ot/lookup.rs
HarfRust declares it's MSRV to be `1.75` (matching `read-fonts`/`skrifa`). However, due to use of an inline const expression (`const { ... }`) it only actually compiles with Rust `1.79`:
- Use a separately declared `const` to lower MSRV back down to `1.75`
- Test MSRV rust version in CI
=> Fix MSRV build and test in CI

Cargo.toml, src/lib.rs
Enable Pedantic clippy lints, while also allowing all the ones that got triggered.  Not all of these lints should be fixed, but this gives a list of things to consider fixing in subsequent PRs.
The list was generated with:
```sh
cargo clippy --all-targets --workspace --all-features --message-format=json --quiet | jq -r '.message.code.code | select(. != null and startswith("clippy::"))' | sort | uniq -c | sort -h -r
```
=> chore: clippy fixes

Cargo.lock, Cargo.toml
This was causing incompatibility with the latest version of skrifa.
=> Update read-fonts dependency to v0.30.1

Cargo.toml, clippy.toml, src/hb/aat_layout_trak_table.rs, src/hb/aat_map.rs, src/hb/buffer.rs, src/hb/common.rs, src/hb/kerning.rs, src/hb/ot/contextual.rs, src/hb/ot/lookup.rs, src/hb/ot_layout_gsubgpos.rs, src/hb/ot_map.rs, src/hb/ot_shape.rs, src/hb/ot_shaper_myanmar.rs, src/hb/ot_shaper_use.rs
Fix inconsistencies in how each identifier is used using `cargo fix`.  This is important because it eliminates inconsistent usage of the same ident within one file - making all references to a type the same.
A few additional minor changes:
* add `clippy.toml` to ensure some edge cases are caught before they are accidentally released
* fix macros to use `$crate` instead of `crate`
=> chore: fix unused_qualifications

Cargo.toml, src/hb/aat_layout_morx_table.rs, src/hb/algs.rs, src/hb/buffer.rs, src/hb/common.rs, src/hb/mod.rs, src/hb/ot_layout_gsubgpos.rs, src/hb/tag.rs, src/hb/ucd_table.rs, src/hb/unicode.rs, src/lib.rs
Used this command:
```sh
__CARGO_FIX_YOLO=1 cargo clippy --fix --allow-dirty --workspace --all-targets --all-features ; cargo fmt
```
and manually reverted a few ones that are part of auto-generated code.
This change makes numbers easier to read, and helps spot various mis-positioned bits in long numbers.
=> chore: cleanup unreadable literals

src/hb/kerning.rs, src/hb/ot_layout.rs, src/hb/ot_layout_gsubgpos.rs
Store these in the context and keep a reference on skipping_iterator_t
=> Precompute matcher state per lookup

src/hb/ot/contextual.rs, src/hb/ot/gpos/mark.rs, src/hb/ot/gsub/ligature.rs, src/hb/ot/gsub/reverse_chain.rs, src/hb/ot_layout_gsubgpos.rs
Going with `mut` was fighting a losing battle with the borrow checker. I made it to passing `&hb_glyph_info_t`. My plan is to use `UnsafeCell` for free vars in `hb_glyph_info_t` so we can modify them without mutability.
=> Pass `&mut hb_glyph_info_t` to match functions

src/hb/ot/lookup.rs
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0695         -0.0698           142           132           142           132
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0635         -0.0642           166           155           165           155
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/harfrust                           -0.0707         -0.0706 …
```
=> [LookupInfo] inline apply()

src/hb/face.rs
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0013         -0.0012           131           131           131           131
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0055         -0.0056           155           154           155           154
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/harfrust                           -0.0211         -0.0210 …
```
=> [face] inline glyph_props

src/hb/cache.rs, src/hb/ot/contextual.rs, src/hb/ot/gpos/pair.rs, src/hb/ot/gsub/ligature.rs, src/hb/ot/lookup.rs, src/hb/ot/mod.rs, src/hb/ot_layout_gsubgpos.rs
Needs Chad's cleanup, but amazing speedup on Roboto:
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0077         -0.0073           117           116           116           115
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0045         -0.0045           130           129           129           129 …
```
=> Implement external caches for LigatureSubset & PairPos

src/hb/ot/contextual.rs
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0817         -0.0817           127           117           126           116
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0852         -0.0846           144           132           143           131
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/harfrust                           +0.0052         +0.0058 …
```
=> Contextual tuning

Cargo.toml, src/hb/aat/layout_common.rs, src/hb/cache.rs, src/hb/face.rs, src/hb/ot/mod.rs, src/hb/ot_layout.rs, src/hb/ot_layout_gsubgpos.rs
The `cache.rs` changes need an expert to do properly.
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0211         -0.0216           118           115           117           115
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0058         -0.0054           131           130           130           129 …
```
=> Cache glyph props

src/hb/ot/lookup.rs, src/hb/ot_layout.rs
This is the optimal order, and how HB does it.
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0406         -0.0396           110           105           109           105
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0164         -0.0162           123           121           122           120
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/harfrust …
```
=> Check lookup digest before anything else

src/hb/ot_layout.rs
Was dropped in d286ebc2a7307291cd48fd5bc3f64b26b2a5d178
=> Err. Gate apply_backward with set-digest again

src/hb/buffer.rs
=> [buffer] inline ensure()

src/hb/ot/gpos/pair.rs, src/hb/ot/gsub/ligature.rs, src/hb/ot/lookup.rs, src/hb/ot_layout_gsubgpos.rs, src/hb/set_digest.rs
From https://github.com/harfbuzz/harfbuzz/pull/5464
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0046         -0.0036           109           109           109           108
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0083         -0.0084           129           128           128           127 …
```
=> Ligature seconds digest

src/hb/ot_layout_gsubgpos.rs
Shows consistent improvements on HR benchmarks.
=> Inline matcher_t::may_skip

src/hb/face.rs, src/hb/ot/gpos/mod.rs, src/hb/ot/gpos/pair.rs, src/hb/ot/gpos/single.rs
This reverts commit 047f9a4b51d0f382f4d7e5b5b50dd0839be99271.
=> Revert "Use the new fontations Value type for all GPOS tables (#161)"

src/hb/ot/contextual.rs, src/hb/ot/gsub/ligature.rs, src/hb/ot_layout_gsubgpos.rs
```
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/harfrust                -0.0391         -0.0387           106           102           105           101
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/harfrust                          -0.0355         -0.0355           125           121           124           120
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/harfrust                           -0.0540         -0.0542 …
```
=> Cache match_positions in the ctx

src/hb/set_digest.rs
This reverts commit 304eae0f24c99fc7c241d7b405578449d76d3c62.
Revert, as this was borderline on slowdown. Let compiler decide. HB reverted as well: https://github.com/harfbuzz/harfbuzz/pull/5470
=> Revert "Branchfree set_digest (#179)"

src/hb/aat/layout_kerx_table.rs
now that this has been fixed in read-fonts
=> [kerx] remove the tuple count guard

src/hb/ot/lookup.rs, src/hb/ot/mod.rs, src/hb/ot_layout.rs, src/hb/ot_layout_gsubgpos.rs
Use a `Vec` of `OnceLock`s so that we can cache lookup metadata on demand rather than preloading all of them.
On `no_std` builds, just precaches everything since we don't have the primitives available to do this safely and thread safely.
=> Implement lazy lookup loading

src/hb/ot_layout_gsubgpos.rs
If the font has a long ligature, we were allocating memory for match-positions even if ligature wouldn't match.
With GoogleSans-Regular.ttf and en-thelittleprince.txt, through hb-harfrust:
Before:
```
total heap usage: 3,169 allocs, 3,156 frees, 451,019 bytes allocated
```
After:
```
total heap usage: 1,912 allocs, 1,899 frees, 362,571 bytes allocated
```
=> Allocate match_positions on-demand

src/hb/ot/gpos/pair.rs, src/hb/ot/gsub/ligature.rs, src/hb/ot/lookup.rs, src/hb/ot/mod.rs, src/hb/ot_layout_gsubgpos.rs, src/hb/set_digest.rs
This adds a secondary set of smaller "caches" for the PairPos and Ligature subtables. This is basically just storing small metadata from Coverage and ClassDef tables so we can avoid a bunch of reads and bounds checks. For ligature subtables, this keeps the "seconds" set digest in the smaller cache but that could be removed.
Based on #192
=> Add smaller, secondary subtable caches

src/hb/aat/layout_kerx_table.rs, src/hb/aat/layout_morx_table.rs, src/hb/aat/mod.rs
With ArialHB.ttc and en-thelittleprince.txt:
```
Benchmark                                                              Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------------------------------------------
BM_Shape/ArialHB.ttc/en-thelittleprince.txt/harfrust                -0.3099         -0.3098            23            16            23            16
```
=> [kerx] Add a class cache

src/hb/ot/gsub/ligature.rs
In the cache with "seconds" set-digest.
From HB https://github.com/harfbuzz/harfbuzz/pull/5500
=> [ligature-cache] Handle case of ligature with no components

Cargo.toml, src/digest_u32_set.rs, src/hb/aat/layout_common.rs, src/hb/aat/layout_kerx_table.rs, src/hb/aat/layout_morx_table.rs, src/hb/aat/mod.rs, src/hb/buffer.rs, src/hb/kerning.rs, src/hb/mod.rs, src/hb/ot/gsub/ligature.rs, src/hb/ot/lookup.rs, src/hb/ot/mod.rs, src/hb/ot_layout.rs, src/hb/ot_layout_gsubgpos.rs, src/hb/set_digest.rs, src/lib.rs
Depends on https://github.com/googlefonts/fontations/pull/1633
=> [aat] Towards adding bitset caches

src/hb/aat/layout.rs, src/hb/aat/layout_common.rs, src/hb/aat/layout_morx_table.rs, src/hb/ot_shape.rs, src/hb/ot_shape_plan.rs
Use it if there's no user features. Reduces mallocs and minor speedup too.
Port of HB e5a01efd07e540f2202d64dbc9372dc6f1be4a1e
=> [aat] Put back one set of compiled map in the plan

src/hb/ot/contextual.rs, src/hb/ot/mod.rs, src/hb/ot_layout_gsubgpos.rs
We have some unused space in the external subtable cache so use it for these tables to avoid some fontations overhead. Seems to buy a little bit on Nastaliq according to HR benches.
=> Minor optimizations for (Chain)ContextFormat2

src/hb/buffer.rs, src/hb/ot_layout.rs, src/hb/ot_layout_gsubgpos.rs, src/hb/ot_shape.rs
We don't have to reinitialize it for GPOS now, showing some 1.5% speedup on Roboto-Regular benchmark.
Over time we can change the various gsub_pauses to update the digest in-place instead of returning true.
From HB https://github.com/harfbuzz/harfbuzz/pull/5576 and b2a6375b8138d1189d6d719a92e9d88b92a0b669
=> [buffer] Retain digest in the buffer

src/hb/buffer.rs, src/hb/ot_layout.rs, src/hb/ot_shape.rs, src/hb/ot_shaper_thai.rs
Use it in form_clusters instead of ascii flag, for speedup.
From HB.
=> [shape] Use a buffer scratch flag for continuations (#5586)
