harfbuzz/harfrust

- README.md
Attempt to address feedback in https://github.com/harfbuzz/harfruzz/pull/2#discussion_r1691552467
@khaledhosny is this version better?
> Fix Arabic shaper bullet

- src/hb/buffer.rs
- src/hb/ot/lookup.rs
- src/hb/ot_layout.rs
- src/hb/ot_layout_gsubgpos.rs
- src/hb/set_digest.rs
A ChatGPT collaboration.
Shows >5% speedup on Roboto shaping in HB benchmark.
> Update set_digest.rs to reflect latest HarfBuzz version

- src/hb/ot/lookup.rs
- src/hb/ot/mod.rs
- src/hb/ot_layout.rs
- src/hb/ot_layout_gsubgpos.rs
This avoids reparsing each subtable per glyph.
> [WIP] Cache parsed subtables per lookup

- benches/src/lib.rs
Before:
```
test arabic::word_1::hb               ... bench:         719.93 ns/iter (+/- 29.34)
test arabic::word_1::hr               ... bench:       6,990.01 ns/iter (+/- 106.21)
```
After:
```
test arabic::word_1::hb               ... bench:         760.67 ns/iter (+/- 82.68)
test arabic::word_1::hr               ... bench:       1,577.32 ns/iter (+/- 71.75)
```
> [benches] Cache shape-plan

- scripts/gen-shaping-tests.py
- src/hb/glyph_metrics.rs
- tests/shaping/in_house.rs
One test failing still. Working on it.
> Enable vertical.tests and improve v_origin

- src/hb/cache.rs
- src/hb/charmap.rs
- src/hb/face.rs
- src/hb/mod.rs
> Add hb_cache_t and use for cmap

- Cargo.lock
- Cargo.toml
- src/hb/aat/mod.rs
- src/hb/aat_layout_common.rs
- src/hb/aat_layout_kerx_table.rs
- src/hb/kerning.rs
- src/hb/ot_layout.rs
Depends on googlefonts/fontations#1519 and a new release.
> use read-fonts kern table; delete ttf-parser dependency

- src/hb/buffer.rs
> Add unsafe_to_concat/safe_to_insert_tatweel

- src/hb/ot/gsub/ligature.rs
- src/hb/ot_layout_gsubgpos.rs
8% speedup in Roboto-Regular shaping.
> [LigatureSet] Port fast-path from HarfBuzz

- src/hb/buffer.rs
- src/hb/ot_layout.rs
- src/hb/ot_layout_gpos_table.rs
- src/hb/ot_shape.rs
- src/hb/ot_shape_fallback.rs
- src/hb/ot_shape_normalize.rs
- src/hb/ot_shaper.rs
- src/hb/ot_shaper_arabic.rs
- src/hb/ot_shaper_hangul.rs
- src/hb/ot_shaper_indic.rs
- src/hb/ot_shaper_khmer.rs
- src/hb/ot_shaper_myanmar.rs
- src/hb/ot_shaper_syllabic.rs
- src/hb/ot_shaper_use.rs
Necessary for porting some of the caches.
> Adapt buffer var allocation bookkeeping from HB

- src/hb/aat_layout_kerx_table.rs
- src/hb/kerning.rs
- src/hb/ot/contextual.rs
- src/hb/ot/gpos/cursive.rs
- src/hb/ot/gpos/mark.rs
- src/hb/ot/gpos/pair.rs
- src/hb/ot/gsub/ligature.rs
- src/hb/ot/lookup.rs
- src/hb/ot_layout_gsubgpos.rs
To support caching through modifying glyph info
@behdad
> Give skippy iter a mutable buffer

- src/hb/ot/contextual.rs
- src/hb/ot/lookup.rs
- src/hb/ot/mod.rs
- src/hb/ot_layout.rs
- src/hb/ot_layout_gsubgpos.rs
Kinda ugly and not ready to merge yet, but worth doing some measurement.
> Subtable dispatch through function pointers

- Cargo.toml
- src/hb/ot/gpos/mod.rs
- src/hb/ot/gpos/pair.rs
- src/hb/ot/gpos/single.rs
- src/hb/ot/mod.rs
ref googlefonts/fontations#1602
> Use PairPos2 fast path from fontations

- src/hb/buffer.rs
https://github.com/harfbuzz/harfrust/pull/147#pullrequestreview-3121342329
> [buffer] Apply review feedback

- src/hb/ot/contextual.rs
- src/hb/ot/gsub/ligature.rs
- src/hb/ot_layout_gsubgpos.rs
> [ligature] Tune slow-path

- src/hb/glyph_metrics.rs
Retain the h_metrics array from hmtx so we don't parse/validate it for each advance width lookup.
> Micro-optimize advance widths

- src/hb/face.rs
- src/hb/ot/gpos/mod.rs
- src/hb/ot/gpos/pair.rs
- src/hb/ot/gpos/single.rs
Updated treatment for pairpos1 and singlepos1/2 to match the work for pairpos2 in #167
Cleans up the code quite a bit so hopefully this one doesn't create any perf regressions.
> Unify on new value record application

- src/hb/buffer.rs
- src/hb/ot_layout.rs
- src/hb/ot_layout_gsubgpos.rs
From https://github.com/harfbuzz/harfbuzz/pull/5420
I can't measure any speedups, not even with Duployan. Investigating.
> Cache props matching

- src/hb/ot_layout_gsubgpos.rs
> Minimize how much match_positions data we copy

- src/hb/ot/gpos/pair.rs
- src/hb/ot/gsub/ligature.rs
Reverts previous commit's panics.
> Don't panic! in the library

- Cargo.toml
> Use read-fonts 0.33.0 from crates.io

- Cargo.toml
- src/hb/aat/layout_morx_table.rs
- src/hb/buffer.rs
- src/hb/face.rs
- src/hb/ot_layout_gsubgpos.rs
- src/hb/ot_shape.rs
> Remove extra buffer enter/leave

- src/hb/ot_layout_gsubgpos.rs
SmallVec takes care of exponential resize for us.
Fixes https://github.com/harfbuzz/harfrust/issues/201
> Simplify match-positions resize logic

- HARFBUZZ.md
After https://github.com/harfbuzz/harfbuzz/pull/5492
> [HARFBUZZ] item-context tests pass now

- src/hb/buffer.rs
- src/hb/ot_layout.rs
- src/hb/ot_layout_gpos_table.rs
- src/hb/ot_layout_gsubgpos.rs
And a couple of compile-time asserts.
These assertions are heavily tested in HB fuzzers. We don't want them at --release time.
> Change all assert!'s into debug_assert!

- src/hb/aat/layout_common.rs
- src/hb/aat/layout_morx_table.rs
- src/hb/aat/mod.rs
With Lucida Grande and en-thelittleprince:
```
Benchmark                                                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_Shape/LucidaGrande.ttc/en-thelittleprince.txt/harfrust                       -0.3677         -0.3674            21            13            21            13
```
> [morx] Add a class-cache

- src/hb/ot_layout_gpos_table.rs
- src/hb/ot_shape.rs
https://github.com/harfbuzz/harfbuzz/pull/5515
> Port attachment propagation fixes from HB

- src/hb/aat/layout.rs
- src/hb/ot_shape.rs
This was not fully ported:
https://github.com/harfbuzz/harfbuzz/pull/5119
> [aat] Port rest of a HB PR re deleted-glyphs

- src/hb/aat/layout_morx_table.rs
> [morx] Inline a lambda

- src/hb/aat/layout_kerx_table.rs
- src/hb/kerning.rs
Fixes https://github.com/harfbuzz/harfrust/issues/225 using copy/pasta.
> [kern/kerx] Update unsafe-to-break logic to latest

- src/hb/aat/layout_kerx_table.rs
- src/hb/aat/layout_morx_table.rs
- src/hb/kerning.rs
I settled for this instead. I think this is more robust than zipping.
> [kern/kerx/morx] Be more defensive against cache/subtables mismatch

- src/hb/aat/layout_common.rs
- src/hb/aat/layout_kerx_table.rs
- src/hb/aat/layout_morx_table.rs
- src/hb/kerning.rs
New optimization. Off to implementing in HB now.
> Aat speedup unsafe to break
